### ISSUE TITLE
Allow importing other files into your project

### ISSUE THREAD

**Issue by sowbug** [sowbug/groove#47]
We'd need modules, namespaces, stuff like that.

Examples:

```yaml
patterns:
  - id: basic-1
    from: bundled/patterns/four-on-the-floor
```
or

```yaml
devices:
  - instrument:
    - piano-1
    - welsh:
        midi-in: 0
        from: local/patches/welsh/funky
```
